const item = {
  QueryResponse: {
    Item: [
      {
        Name: "Cedar",
        Active: true,
        FullyQualifiedName: "Cedar",
        Type: "Category",
        domain: "QBO",
        sparse: false,
        Id: "23",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-05-02T07:36:51-07:00",
          LastUpdatedTime: "2021-05-02T07:36:51-07:00",
        },
      },
      {
        Name: "Cedsar",
        Active: true,
        FullyQualifiedName: "Cedsar",
        Type: "Category",
        domain: "QBO",
        sparse: false,
        Id: "24",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-05-02T07:38:34-07:00",
          LastUpdatedTime: "2021-05-02T07:38:34-07:00",
        },
      },
      {
        Name: "Concrete",
        Description: "Concrete for fountain installation",
        Active: true,
        FullyQualifiedName: "Concrete",
        Taxable: true,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "48",
          name: "Fountains and Garden Lighting",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "3",
        SyncToken: "1",
        MetaData: {
          CreateTime: "2021-03-20T10:36:03-07:00",
          LastUpdatedTime: "2021-03-23T12:47:47-07:00",
        },
      },
      {
        Name: "Design",
        Description: "Custom Design",
        Active: true,
        FullyQualifiedName: "Design",
        Taxable: false,
        UnitPrice: 75,
        Type: "Service",
        IncomeAccountRef: {
          value: "82",
          name: "Design income",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "4",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:41:38-07:00",
          LastUpdatedTime: "2021-03-20T10:41:38-07:00",
        },
      },
      {
        Name: "Garden fsfSupplies",
        Active: true,
        FullyQualifiedName: "Garden fsfSupplies",
        Type: "Category",
        domain: "QBO",
        sparse: false,
        Id: "21",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-05-02T07:35:12-07:00",
          LastUpdatedTime: "2021-05-02T07:35:43-07:00",
        },
      },
      {
        Name: "Cedar",
        Active: true,
        SubItem: true,
        ParentRef: {
          value: "21",
          name: "Garden fsfSupplies",
        },
        Level: 1,
        FullyQualifiedName: "Garden fsfSupplies:Cedar",
        Type: "Category",
        domain: "QBO",
        sparse: false,
        Id: "22",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-05-02T07:35:43-07:00",
          LastUpdatedTime: "2021-05-02T07:35:43-07:00",
        },
      },
      {
        Name: "Garden Supplies",
        Active: true,
        FullyQualifiedName: "Garden Supplies",
        Taxable: false,
        UnitPrice: 0,
        Type: "Inventory",
        IncomeAccountRef: {
          value: "79",
          name: "Sales of Product Income",
        },
        PurchaseCost: 0,
        ExpenseAccountRef: {
          value: "80",
          name: "Cost of Goods Sold",
        },
        AssetAccountRef: {
          value: "81",
          name: "Inventory Asset",
        },
        TrackQtyOnHand: true,
        QtyOnHand: 10,
        InvStartDate: "2015-01-01",
        domain: "QBO",
        sparse: false,
        Id: "19",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-05-02T07:26:51-07:00",
          LastUpdatedTime: "2021-05-02T07:26:51-07:00",
        },
      },
      {
        Name: "Gardening",
        Description: "Weekly Gardening Service",
        Active: true,
        FullyQualifiedName: "Gardening",
        Taxable: false,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "45",
          name: "Landscaping Services",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "6",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:43:14-07:00",
          LastUpdatedTime: "2021-03-20T10:43:14-07:00",
        },
      },
      {
        Name: "Hours",
        Active: true,
        FullyQualifiedName: "Hours",
        Taxable: false,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "1",
          name: "Services",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "2",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-15T14:42:05-07:00",
          LastUpdatedTime: "2021-03-15T14:42:05-07:00",
        },
      },
      {
        Name: "Installation",
        Description: "Installation of landscape design",
        Active: true,
        FullyQualifiedName: "Installation",
        Taxable: false,
        UnitPrice: 50,
        Type: "Service",
        IncomeAccountRef: {
          value: "52",
          name: "Installation",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "7",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:43:54-07:00",
          LastUpdatedTime: "2021-03-20T10:43:54-07:00",
        },
      },
      {
        Name: "Lighting",
        Description: "Garden Lighting",
        Active: true,
        FullyQualifiedName: "Lighting",
        Taxable: true,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "48",
          name: "Fountains and Garden Lighting",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "8",
        SyncToken: "1",
        MetaData: {
          CreateTime: "2021-03-20T10:44:40-07:00",
          LastUpdatedTime: "2021-03-23T12:47:38-07:00",
        },
      },
      {
        Name: "Maintenance & Repair",
        Description: "Maintenance & Repair",
        Active: true,
        FullyQualifiedName: "Maintenance & Repair",
        Taxable: false,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "53",
          name: "Maintenance and Repair",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "9",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:45:18-07:00",
          LastUpdatedTime: "2021-03-20T10:45:18-07:00",
        },
      },
      {
        Name: "Pest Control",
        Description: "Pest Control Services",
        Active: true,
        FullyQualifiedName: "Pest Control",
        Taxable: false,
        UnitPrice: 35,
        Type: "Service",
        IncomeAccountRef: {
          value: "54",
          name: "Pest Control Services",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "10",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:45:49-07:00",
          LastUpdatedTime: "2021-03-20T10:45:49-07:00",
        },
      },
      {
        Name: "Pump",
        Description: "Fountain Pump",
        Active: true,
        FullyQualifiedName: "Pump",
        Taxable: true,
        UnitPrice: 15,
        Type: "Inventory",
        IncomeAccountRef: {
          value: "79",
          name: "Sales of Product Income",
        },
        PurchaseDesc: "Fountain Pump",
        PurchaseCost: 10,
        ExpenseAccountRef: {
          value: "80",
          name: "Cost of Goods Sold",
        },
        AssetAccountRef: {
          value: "81",
          name: "Inventory Asset",
        },
        TrackQtyOnHand: true,
        QtyOnHand: 26,
        InvStartDate: "2021-03-23",
        domain: "QBO",
        sparse: false,
        Id: "11",
        SyncToken: "3",
        MetaData: {
          CreateTime: "2021-03-20T10:46:45-07:00",
          LastUpdatedTime: "2021-04-30T08:25:26-07:00",
        },
      },
      {
        Name: "Refunds & Allowances",
        Description: "Income due to refunds or allowances",
        Active: true,
        FullyQualifiedName: "Refunds & Allowances",
        Taxable: false,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "83",
          name: "Other Income",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "12",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:49:18-07:00",
          LastUpdatedTime: "2021-03-20T10:49:18-07:00",
        },
      },
      {
        Name: "Rock Founstain",
        Description: "New, updated description for Rock Fountain",
        Active: true,
        FullyQualifiedName: "Rock Founstain",
        Taxable: true,
        UnitPrice: 275,
        Type: "Inventory",
        IncomeAccountRef: {
          value: "79",
          name: "Sales of Product Income",
        },
        PurchaseDesc: "Rock Fountain",
        PurchaseCost: 125,
        ExpenseAccountRef: {
          value: "80",
          name: "Cost of Goods Sold",
        },
        AssetAccountRef: {
          value: "81",
          name: "Inventory Asset",
        },
        TrackQtyOnHand: true,
        QtyOnHand: 2,
        InvStartDate: "2015-01-01",
        domain: "QBO",
        sparse: false,
        Id: "20",
        SyncToken: "2",
        MetaData: {
          CreateTime: "2021-05-02T07:34:47-07:00",
          LastUpdatedTime: "2021-05-02T07:59:57-07:00",
        },
      },
      {
        Name: "Rock Fountain",
        Description: "Rock Fountain",
        Active: true,
        FullyQualifiedName: "Rock Fountain",
        Taxable: true,
        UnitPrice: 275,
        Type: "Inventory",
        IncomeAccountRef: {
          value: "79",
          name: "Sales of Product Income",
        },
        PurchaseDesc: "Rock Fountain",
        PurchaseCost: 125,
        ExpenseAccountRef: {
          value: "80",
          name: "Cost of Goods Sold",
        },
        AssetAccountRef: {
          value: "81",
          name: "Inventory Asset",
        },
        TrackQtyOnHand: true,
        QtyOnHand: 3,
        InvStartDate: "2021-03-23",
        domain: "QBO",
        sparse: false,
        Id: "5",
        SyncToken: "2",
        MetaData: {
          CreateTime: "2021-03-20T10:42:19-07:00",
          LastUpdatedTime: "2021-04-30T08:25:26-07:00",
        },
      },
      {
        Name: "Rocks",
        Description: "Garden Rocks",
        Active: true,
        FullyQualifiedName: "Rocks",
        Taxable: true,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "48",
          name: "Fountains and Garden Lighting",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "13",
        SyncToken: "1",
        MetaData: {
          CreateTime: "2021-03-20T10:50:11-07:00",
          LastUpdatedTime: "2021-03-23T12:47:31-07:00",
        },
      },
      {
        Name: "Services",
        Active: true,
        FullyQualifiedName: "Services",
        Taxable: false,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "1",
          name: "Services",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "1",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-15T14:42:05-07:00",
          LastUpdatedTime: "2021-03-15T14:42:05-07:00",
        },
      },
      {
        Name: "Sod",
        Description: "Sod",
        Active: true,
        FullyQualifiedName: "Sod",
        Taxable: true,
        UnitPrice: 0,
        Type: "Service",
        IncomeAccountRef: {
          value: "49",
          name: "Plants and Soil",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "14",
        SyncToken: "1",
        MetaData: {
          CreateTime: "2021-03-20T10:50:45-07:00",
          LastUpdatedTime: "2021-03-23T12:47:22-07:00",
        },
      },
      {
        Name: "Soil",
        Description: "2 cubic ft. bag",
        Active: true,
        FullyQualifiedName: "Soil",
        Taxable: true,
        UnitPrice: 10,
        Type: "Service",
        IncomeAccountRef: {
          value: "49",
          name: "Plants and Soil",
        },
        PurchaseDesc: "2 cubic ft. bag",
        PurchaseCost: 6.5,
        ExpenseAccountRef: {
          value: "66",
          name: "Plants and Soil",
        },
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "15",
        SyncToken: "2",
        MetaData: {
          CreateTime: "2021-03-20T10:51:28-07:00",
          LastUpdatedTime: "2021-03-23T12:47:25-07:00",
        },
      },
      {
        Name: "Sprinkler Heads",
        Description: "Sprinkler Heads",
        Active: true,
        FullyQualifiedName: "Sprinkler Heads",
        Taxable: true,
        UnitPrice: 2,
        Type: "Inventory",
        IncomeAccountRef: {
          value: "79",
          name: "Sales of Product Income",
        },
        PurchaseDesc: "Sprinkler Heads",
        PurchaseCost: 0.75,
        ExpenseAccountRef: {
          value: "80",
          name: "Cost of Goods Sold",
        },
        AssetAccountRef: {
          value: "81",
          name: "Inventory Asset",
        },
        TrackQtyOnHand: true,
        QtyOnHand: 25,
        InvStartDate: "2021-03-23",
        domain: "QBO",
        sparse: false,
        Id: "16",
        SyncToken: "3",
        MetaData: {
          CreateTime: "2021-03-20T10:51:50-07:00",
          LastUpdatedTime: "2021-03-23T12:51:47-07:00",
        },
      },
      {
        Name: "Sprinkler Pipes",
        Description: "Sprinkler Pipes",
        Active: true,
        FullyQualifiedName: "Sprinkler Pipes",
        Taxable: true,
        UnitPrice: 4,
        Type: "Inventory",
        IncomeAccountRef: {
          value: "79",
          name: "Sales of Product Income",
        },
        PurchaseDesc: "Sprinkler Pipes",
        PurchaseCost: 2.5,
        ExpenseAccountRef: {
          value: "80",
          name: "Cost of Goods Sold",
        },
        AssetAccountRef: {
          value: "81",
          name: "Inventory Asset",
        },
        TrackQtyOnHand: true,
        QtyOnHand: 31,
        InvStartDate: "2021-03-23",
        domain: "QBO",
        sparse: false,
        Id: "17",
        SyncToken: "3",
        MetaData: {
          CreateTime: "2021-03-20T10:52:07-07:00",
          LastUpdatedTime: "2021-03-23T12:57:24-07:00",
        },
      },
      {
        Name: "Trimming",
        Description: "Tree and Shrub Trimming",
        Active: true,
        FullyQualifiedName: "Trimming",
        Taxable: false,
        UnitPrice: 35,
        Type: "Service",
        IncomeAccountRef: {
          value: "45",
          name: "Landscaping Services",
        },
        PurchaseCost: 0,
        TrackQtyOnHand: false,
        domain: "QBO",
        sparse: false,
        Id: "18",
        SyncToken: "0",
        MetaData: {
          CreateTime: "2021-03-20T10:52:42-07:00",
          LastUpdatedTime: "2021-03-20T10:52:42-07:00",
        },
      },
    ],
    startPosition: 1,
    maxResults: 24,
  },
  time: "2021-05-04T21:49:54.822-07:00",
};
